language: python

env:
  global:
    - CIBW_SKIP="pp* cp27-* cp34-* cp35-* cp36-* *i686* *-win32"
    - CIBW_BEFORE_BUILD="pip install numpy&&python setup.py build_ext --inplace"
    - CIBW_BEFORE_TEST="pip install -r requirements-dev.txt"
    - CIBW_TEST_REQUIRES=pytest
    - CIBW_TEST_COMMAND="pytest {project}"

jobs:
  include:
    # perform a linux build
    - services: docker
    # and a mac build
    - os: osx
      language: shell
      before_install:
      - brew install gcc@7
      - export CC=gcc-7
      - export CXX=g++-7
      - alias python=python3
    # and a windows build
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"

install:
  - python3 -m pip install cibuildwheel==1.5.5

script:
  # build the wheels, put them into './wheelhouse'
  - python3 -m cibuildwheel --output-dir wheelhouse

deploy:
  provider: s3
  access_key_id: AKIAIH6I45BAJIHWYAAQ
  secret_access_key: $AWS_SECRET_KEY
  bucket: "traviscibucket"
  upload_dir: $TRAVIS_REPO_SLUG/$TRAVIS_BRANCH/$TRAVIS_BUILD_NUMBER.$TRAVIS_COMMIT/$TRAVIS_JOB_NAME
  local_dir: $TRAVIS_BUILD_DIR/wheelhouse
  skip_cleanup: true
  on:
    all_branches: true

notifications:
  email:
    recipients:
    - carlk@msn.com
    on_success: always
    on_failure: always
