name: Rust

on:
  push:
    
env:
  CARGO_TERM_COLOR: always

# Good examples:
#    https://github.com/Intsights/fastzy/blob/152aecbb05302b0f8db7f23b0242b448ec5e6435/.github/workflows/deploy.yml
#    https://github.com/polkascan/py-ed25519-bindings/blob/96638152c1902d917b8ec29adabe9cc8c3519086/.github/workflows/test.yml
#    https://github.com/OpenMined/syft_experimental/blob/6630fec206d153fb5a94ad8c5365636ee462ecd9/.github/workflows/python.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install latest rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip maturin
    # cmk        
    # - name: Rust tests
    #   run: cargo test --verbose
    # make 3.8 a variable.
    - name: Build wheel with Maturin (and list)
      run: |
        maturin build --release -i python3.8
        ls -las target/wheels
    - name: Install virtualenv for testing
      run: |
        pip install virtualenv
        virtualenv testing --system-site-packages
        source testing/bin/activate
    - name: Install dependencies from wheel
      run: |
        pip install target/wheels/*.whl
        pip uninstall bed-reader --yes
    - name: Install package in dev mode
      run: maturin develop
    - name: Install test dependencies
      run: pip install -r requirements-dev.txt
    - name: Python tests
      run: pytest bed_reader
