name: just_test

on:
  # push:
  workflow_dispatch:
    
env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install flake8, etc
      run: |
        cd bed_reader
        pwd
        python -m pip install --upgrade pip
        pip install flake8 pytest black isort --upgrade
    - name: Lint with flake8, etc
      run: |
        echo "flake8"
        flake8 .
        echo "black"
        black --version
        black --verbose --check .
        echo "isort"
        isort --check-only .
    - name: Test Python - Non-Windows
      if: runner.os != 'Windows'
      run: |
        pip install virtualenv
        virtualenv vEnv; source vEnv/bin/activate
        python -m pip install --upgrade pip maturin
        maturin develop
        echo "requirements"
        pip install -r requirements.txt
        echo "requirements-dev"
        pip install -r requirements-dev.txt
        pytest bed_reader
    - name: Test Python - Windows
      if: runner.os == 'Windows'
      run: |
        pip install virtualenv
        virtualenv vEnv; vEnv\Scripts\activate.ps1
        echo "pwd"
        pwd
        python -m pip install --upgrade pip maturin
        echo "requirements"
        pip install -r requirements.txt
        echo "requirements-dev"
        pip install -r requirements-dev.txt
        echo "maturin"
        maturin develop
        echo "pytest"
        pytest bed_reader