name: Rust

on:
  push:
    
env:
  CARGO_TERM_COLOR: always

# Good examples:
#    https://github.com/Intsights/fastzy/blob/152aecbb05302b0f8db7f23b0242b448ec5e6435/.github/workflows/deploy.yml  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install latest rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip maturin
    # cmk        
    # - name: Rust tests
    #   run: cargo test --verbose
    # make 3.8 a variable
    - name: Build with Maturin
      run: maturin build --release -i python3.8
    - name: See Results
      run: ls -las target/wheels
    - name: Python tests
      run: |
        # python -m pip install --user virtualenv
        # maturin develop --release
        # pip install -r requirements.txt
        pip install target/wheels/*.whl
        cd bed_reader
        pytest .
        cd ..
