name: updown

on:
  push:
  workflow_dispatch:
    
env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64]
    steps:
      - name: create file
        run: |
          mkdir -p dist
          cd dist
          echo "test" > test.txt
          ls -las
      - name: Upload test.txt
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist
  
  test:
    name: Test
    needs: [linux]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist
      - name: Install wheels
        run: |
          ls -las
          ls -las dist
